### ISSUE TITLE
Upload dummy datasets to public platform

### ISSUE THREAD

**Issue by ecarrenolozano** [biocypher/DFG528753569#14]
-  [ ] Upload dummy graph datasets on a public platform accessible for reproducible experimentation.
    - Note: all the datasets **MUST NOT** contain real data.

**Comment by ecarrenolozano** [comment]
**Platform:** Open Science Framework
**Link:** https://osf.io/r9vj6/files/osfstorage

**Comment by slobentanzer** [comment]
Good point, but I would recommend Zenodo, as it is more the standard in our field (compare https://zenodo.org/records/7773985). :)

**Comment by ecarrenolozano** [comment]
> Good point, but I would recommend Zenodo, as it is more the standard in our field (compare https://zenodo.org/records/7773985). :)

How can I upload data to the BioCypher Zenodo space? For now, the OSF is a temporal solution 👍🏼

**Comment by slobentanzer** [comment]
There is no BioCypher space on Zenodo; I just linked my own Zenodo account to the GitHub account. You can upload any data through your account.

**Comment by ecarrenolozano** [comment]
**Platform:** Zenodo
**Link:** https://zenodo.org/api/records/14327409/files-archive

**Comment by ecarrenolozano** [comment]
Status 100%
Done: Next steps will be to post link on Mkdocs webpage.
